services:
  mongo:
    image: mongo:5.0
    deploy:
      resources:
        limits:
          memory: 512m
    restart: always
    command: --replSet rs0 --bind_ip_all --keyFile /tmp/file.key
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: "mongo-user"
      MONGO_INITDB_ROOT_PASSWORD: "mongo-password"
    healthcheck:
      test: test $$(mongosh -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet --eval "rs.initiate().ok || rs.status().ok") -eq 1
      interval: 10s
      retries: 20
    ports:
      - "27017:27017"
    volumes:
      - ./init/mongo/init.sh:/docker-entrypoint-initdb.d/init-mongo.sh